jobs:
  - job: Build_PS_Win2016
    pool:
      vmImage: vs2017-win2016
    steps:
    - powershell: |
        Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck
        .\PSEventViewer.Tests.ps1 -Verbose
      displayName: 'Run Pester Tests'